%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.8.0

-ifndef(chat_pb).
-define(chat_pb, true).

-define(chat_pb_gpb_version, "4.8.0").

-ifndef('P_MSG_PB_H').
-define('P_MSG_PB_H', true).
-record(p_msg,
        {msg_type               :: integer(),       % = 1, 32 bits
         text_msg               :: iodata() | undefined, % = 2
         pic                    :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('CS_CHAT_SINGLE_PB_H').
-define('CS_CHAT_SINGLE_PB_H', true).
-record(cs_chat_single,
        {receiver_id            :: integer(),       % = 1, 32 bits
         msg                    :: chat_pb:p_msg()  % = 2
        }).
-endif.

-ifndef('SC_CHAT_SINGLE_PB_H').
-define('SC_CHAT_SINGLE_PB_H', true).
-record(sc_chat_single,
        {result                 :: integer(),       % = 1, 32 bits
         msg_id                 :: integer()        % = 2, 32 bits
        }).
-endif.

-ifndef('CS_CHAT_GROUP_PB_H').
-define('CS_CHAT_GROUP_PB_H', true).
-record(cs_chat_group,
        {group_id               :: integer(),       % = 1, 32 bits
         msg                    :: chat_pb:p_msg()  % = 2
        }).
-endif.

-ifndef('SC_CHAT_GROUP_PB_H').
-define('SC_CHAT_GROUP_PB_H', true).
-record(sc_chat_group,
        {result                 :: integer(),       % = 1, 32 bits
         msg_id                 :: integer()        % = 2, 32 bits
        }).
-endif.

-ifndef('SC_CHAT_MSG_NOTIFY_PB_H').
-define('SC_CHAT_MSG_NOTIFY_PB_H', true).
-record(sc_chat_msg_notify,
        {sender_id              :: integer(),       % = 1, 32 bits
         group_id               :: integer() | undefined, % = 2, 32 bits
         msg_id                 :: integer(),       % = 3, 32 bits
         time                   :: integer(),       % = 4, 32 bits
         msg                    :: chat_pb:p_msg()  % = 5
        }).
-endif.

-endif.
