%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.8.0

-ifndef(chat_pb).
-define(chat_pb, true).

-define(chat_pb_gpb_version, "4.8.0").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record(person,
        {age                    :: integer(),       % = 1, 32 bits
         name                   :: iodata()         % = 2
        }).
-endif.

-endif.
