%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.8.0

-ifndef(chat_pb).
-define(chat_pb, true).

-define(chat_pb_gpb_version, "4.8.0").


-endif.
