%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.8.0

-ifndef(im_pb).
-define(im_pb, true).

-define(im_pb_gpb_version, "4.8.0").

-ifndef('UP_PB_H').
-define('UP_PB_H', true).
-record(up,
        {friend_fun             :: im_pb:cs_friend() | undefined % = 1
        }).
-endif.

-ifndef('DOWN_PB_H').
-define('DOWN_PB_H', true).
-record(down,
        {friend_fun             :: im_pb:sc_friend() | undefined % = 1
        }).
-endif.

-ifndef('CS_FRIEND_PB_H').
-define('CS_FRIEND_PB_H', true).
-record(cs_friend,
        {fetch_all_friends      :: im_pb:cs_fetch_all_friends() | undefined % = 1
        }).
-endif.

-ifndef('SC_FRIEND_PB_H').
-define('SC_FRIEND_PB_H', true).
-record(sc_friend,
        {fetch_all_friends      :: im_pb:sc_fetch_all_friends() | undefined % = 1
        }).
-endif.

-ifndef('CS_FETCH_ALL_FRIENDS_PB_H').
-define('CS_FETCH_ALL_FRIENDS_PB_H', true).
-record(cs_fetch_all_friends,
        {
        }).
-endif.

-ifndef('SC_FETCH_ALL_FRIENDS_PB_H').
-define('SC_FETCH_ALL_FRIENDS_PB_H', true).
-record(sc_fetch_all_friends,
        {frends = []            :: [im_pb:p_frend()] | undefined % = 1
        }).
-endif.

-ifndef('P_FREND_PB_H').
-define('P_FREND_PB_H', true).
-record(p_frend,
        {user_id                :: integer(),       % = 1, 32 bits
         nickname               :: iodata()         % = 2
        }).
-endif.

-endif.
